### PR TITLE
Corrected an issue in replaceVariable that was not adding padding in …

### PR DESCRIPTION
**Pull request by Bouloulou1138**
... tokenized expression

### CODE REVIEW

**Review by mdibaiee — APPROVED** [review]
Thank you!

**Comment by mdibaiee** [comment]
Released as candidate for now: @Bouloulou1138 
https://hackage.haskell.org/package/mathexpr-0.3.1.0/candidate

If it works for you, please let me know so I can publish this new version. Thank you

**Comment by Bouloulou1138** [comment]
Do you know how can I link the candidate build from Hackage? I didn't find a way to do it in my stack project.

**Comment by mdibaiee** [comment]
@Bouloulou1138 I just published it as 0.3.1.0 on hackage, it should be part of the next snapshot of stackage tomorrow I think: https://www.stackage.org/nightly-2022-07-15 (this is 404 today)

**Pull request merged**
